#!/usr/bin/env bash
THIS_DIR=$(cd "$(dirname "$0")"; pwd)


# autolauncher
autolaunchmod() {
		for nms in config-* ; do
			tab="${nms%.*}"
			number="${tab/*-/}"
			tmux kill-session -t cli-$number
			TMUX= tmux new-session -d -s cli-$number "./bot $number" 
			tmux detach -s cli-$number
			sleep 2
		done
		echo -e "Bots are running!"
}
# clear a bot
clr() {
	#rm -rf sessions/nms-"$1".session
	#rm -rf sessions/nms-"$1".session-journal
	#rm -rf config-"$1" 
	redis-cli --raw keys "nms$1*" | xargs redis-cli del
	printf 'DONE !'
}
install() {

		
printf 'Installing ... !'
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install git wget screen tmux make unzip redis-server software-properties-common tor
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get -y update
sudo apt-get -y install python3.7
sudo apt-get -y install python3.7-dev
wget https://bootstrap.pypa.io/get-pip.py
python3.7 get-pip.py
sudo rm -rf get-pip.py
pip3.7 install setuptools
pip3.7 uninstall -y requests
pip3.7 install requests
pip3.7 install requests[socks]
pip3.7 install pyrogram[fast]
pip3.7 install redis


		

printf 'DONE !'
printf 'By Purya'

}

cd "$THIS_DIR" || exit
case $1 in
	install)
		install
	;;
	autolaunch)
		tmux kill-session -t autolaunch-cli
		tmux new-session -s autolaunch-cli "bash bot autolaunchmod"
	;;
	autolaunchmod)
		autolaunchmod
	;;
	clr*)
		id="${1/clr/}"
		clr "$id"
	;;
	*)
		while true ; do
		./purya "$1"
		sleep 5
		done
		
	;;
esac
